### ISSUE TITLE
Cant get back into WebUI

### ISSUE THREAD

**Issue by unicron0827** [ErsatzTV/ErsatzTV#1627]
Im in the process of getting my ErsatzTV all set up.
System is Win10 w/ Plex server and Ersatx on same server box.
Installed Ersatz via GitHub.
Started building collections channels etc, waited for the syncs to finish and Windows rebooted overnight fro an update.
Now I cant get back in.
App opens to system tray, go to UI and get a connection refused.
Checked firewall. no issues, Disabled firewall to be sure, same problem

Check logs and see this.

2024-02-17 14:30:18.901 -05:00 [FTL] Host terminated unexpectedly
System.IO.FileNotFoundException:
File name: 'ErsatzTV.Infrastructure.Sqlite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
at ErsatzTV.Startup.ConfigureServices(IServiceCollection services)
at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>cDisplayClass7_0.<UseStartup>b0(HostBuilderContext context, IServiceCollection services)
at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at ErsatzTV.Program.Main(String[] args) in D:\a\ErsatzTV\ErsatzTV\ErsatzTV\Program.cs:line 110

Didnt make any changes to SQL on my system, and didnt see anything in setup guide that SQL was needed.
Also do not HAVE a D: drive.
os on C
Media on P

So far I have gone through and deleted the Ersatz TV folders, to try and start from scratch with no luck. 

Please advise

**Comment by jasongdove** [comment]
I would confirm that you don't have an antivirus deleting things from the location where you extract the (entire) ErsatzTV zip. The Sqlite library should be bundled/included in the zip.

Also, the D drive letter from the stack trace is just where GitHub places the source code when it compiles the executable. Doesn't have anything to do with your machine.

**Comment by unicron0827** [comment]
> I would confirm that you don't have an antivirus deleting things from the location where you extract the (entire) ErsatzTV zip. The Sqlite library should be bundled/included in the zip.
> 
> Also, the D drive letter from the stack trace is just where GitHub places the source code when it compiles the executable. Doesn't have anything to do with your machine.

Checked that. completely removed AV, re-downloaded and re-extracted Ersatz, still no luck.

**Comment by jasongdove** [comment]
To clarify some process assumptions - can you try

1. Downloading the latest windows release zip https://github.com/ErsatzTV/ErsatzTV/releases/download/v0.8.6-beta/ErsatzTV-v0.8.6-beta-win-x64.zip
2. Extracting it to an empty folder
3. Running ErsatzTV-Windows.exe

When you do that, do you get the same result?
