### ISSUE TITLE
Adding to empty playlist (from library view) does not work; causes soft-crash

### ISSUE THREAD

**Issue by ShadowJonathan** [ErsatzTV/ErsatzTV#1781]
I loaded some videos via an OtherVideos library, and attempted to add them to a playlist, but the moment i click "add", the application crashes and i see the following error in the server logs;

```
ersatztv  | [22:01:15 ERR] Unhandled exception in circuit '[REDACTED]'.
ersatztv  | System.InvalidOperationException: Sequence contains no elements
ersatztv  |    at System.Linq.ThrowHelper.ThrowNoElementsException()
ersatztv  |    at System.Linq.Enumerable.MaxInteger[TSource,TResult](IEnumerable`1 source, Func`2 selector)
ersatztv  |    at ErsatzTV.Application.MediaCollections.AddItemsToPlaylistHandler.ApplyAddItemsRequest(TvContext dbContext, Playlist playlist, AddItemsToPlaylist request) in /source/ErsatzTV.Application/MediaCollections/Commands/AddItemsToPlaylistHandler.cs:line 51
ersatztv  |    at ErsatzTV.Core.LanguageExtensions.<>c__DisplayClass2_0`2.<<Apply>b__0>d.MoveNext() in /source/ErsatzTV.Core/LanguageExtensions.cs:line 21
ersatztv  | --- End of stack trace from previous location ---
ersatztv  |    at ErsatzTV.Application.MediaCollections.AddItemsToPlaylistHandler.Handle(AddItemsToPlaylist request, CancellationToken cancellationToken) in /source/ErsatzTV.Application/MediaCollections/Commands/AddItemsToPlaylistHandler.cs:line 30
ersatztv  |    at ErsatzTV.Application.MediaCollections.AddItemsToPlaylistHandler.Handle(AddItemsToPlaylist request, CancellationToken cancellationToken) in /source/ErsatzTV.Application/MediaCollections/Commands/AddItemsToPlaylistHandler.cs:line 30
ersatztv  |    at ErsatzTV.Pages.MultiSelectBase`1.AddItemsToPlaylist(List`1 movieIds, List`1 showIds, List`1 seasonIds, List`1 episodeIds, List`1 artistIds, List`1 musicVideoIds, List`1 otherVideoIds, List`1 songIds, List`1 imageIds, String entityName) in /source/ErsatzTV/Pages/MultiSelectBase.cs:line 225
ersatztv  |    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
ersatztv  |    at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
ersatztv  |    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

I'm using `0.8.7-beta-docker-nvidia`

**Comment by ShadowJonathan** [comment]
Looking at the code, this is caused by this line;

https://github.com/ErsatzTV/ErsatzTV/blob/a0a047ba185f34a18567d7d6b963bf209665e1ad/ErsatzTV.Application/MediaCollections/Commands/AddItemsToPlaylistHandler.cs#L51

I can't add items to a playlist, because the playlist has no items, causing this crash :/

**Comment by ShadowJonathan** [comment]
I worked around this by going to the playlist itself and adding an unrelated item, and then going back to the library/othervideos view and adding all of the videos from there, it worked.

**Comment by jasongdove** [comment]
Thanks for the report, will fix.
