### ISSUE TITLE
NFO parsing error doesn't list filename in log

### ISSUE THREAD

**Issue by kdrudy** [ErsatzTV/ErsatzTV#1938]
It would be super handy for the filename that generated an NFO parsing error to be listed in the log.  Currently the log for a parsing error looks like this:

```
2024-11-17 03:34:04.392 -06:00 [WRN] Error reading string content from NFO 
System.Xml.XmlException: An error occurred while parsing EntityName. Line 4, position 16.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, Int32 lineNo, Int32 linePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReferenceAsync(Boolean isInAttributeValue, EntityExpandType expandType)
   at System.Xml.XmlTextReaderImpl.ParseTextAsync_ParseEntity(Int32 outOrChars, Char[] chars, Int32 pos, Int32 rcount, Int32 rpos, Int32 orChars, Char c)
   at System.Xml.XmlTextReaderImpl.ParseTextAsync_AsyncFunc(Task`1 task)
   at System.Xml.XmlTextReaderImpl.FinishPartialValueAsync()
   at System.Xml.XmlTextReaderImpl._GetValueAsync()
   at System.Xml.XmlReader.InternalReadContentAsStringAsync()
   at System.Xml.XmlReader.ReadElementContentAsStringAsync()
   at ErsatzTV.Scanner.Core.Metadata.Nfo.NfoReader`1.ReadStringContent(XmlReader reader, T nfo, Action`2 action) in /source/ErsatzTV.Scanner/Core/Metadata/Nfo/NfoReader.cs:line 46
```

With hundreds of NFO files being parsed, it would be handy to know the file that generated this error so I can more quickly go and fix it.

**Comment by jasongdove** [comment]
For now if you set scanning log level to debug it should list each file that it's processing.

**Comment by kdrudy** [comment]
Oh that's fair I did not realize that. I will have to try that, thank you.
