### ISSUE TITLE
Health check issue

### ISSUE THREAD

**Issue by n4tur3502** [ErsatzTV/ErsatzTV#915]
Hello, I just noticed I have an error that says "Health check failure; see logs" in the log all i can see is Failed to run health check Unavailable. I am running this on ubuntu server 22.04 with a gtx 960 in it for transcoding.

**Comment by jasongdove** [comment]
I think this has to do with some data that was incompletely removed from the database. Which kind of media libraries do you use? Local? Plex?

**Comment by boroborob** [comment]
Hi!

I have the same in my logs since the start:

3/28/2023 4:24:09 PM +02:00 | Warning | Failed to run health check Unavailable

I am only using Jellyfin libraries.
Both Jellyfin and ErsatzTV are running in docker on the same Unraid server.

**Comment by boroborob** [comment]
Might be a bit late, but here are some more logs:

`[10:55:01 WRN] Failed to run health check Unavailable
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'mediaItem')
   at ErsatzTV.Core.Extensions.MediaItemExtensions.GetHeadVersion(MediaItem mediaItem) in /source/ErsatzTV.Core/Extensions/MediaItemExtensions.cs:line 35
   at ErsatzTV.Core.Extensions.MediaItemExtensions.GetLocalPath(MediaItem mediaItem, IPlexPathReplacementService plexPathReplacementService, IJellyfinPathReplacementService jellyfinPathReplacementService, IEmbyPathReplacementService embyPathReplacementService, Boolean log) in /source/ErsatzTV.Core/Extensions/MediaItemExtensions.cs:line 45
   at ErsatzTV.Infrastructure.Health.Checks.UnavailableHealthCheck.Check(CancellationToken cancellationToken) in /source/ErsatzTV.Infrastructure/Health/Checks/UnavailableHealthCheck.cs:line 69
   at ErsatzTV.Infrastructure.Health.Checks.UnavailableHealthCheck.Check(CancellationToken cancellationToken) in /source/ErsatzTV.Infrastructure/Health/Checks/UnavailableHealthCheck.cs:line 89
   at LanguageExt.Prelude.<>c__DisplayClass1465_0`1.<<TryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at TryAsyncExtensions.Try[T](TryAsync`1 self)`
